// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiJdVLhqCT-dhoYXnHxpemiU-_EA_LkOI',
    appId: '1:1046347342722:web:87de2bc96daec1f9a2a59b',
    messagingSenderId: '1046347342722',
    projectId: 'tbcare-b9252',
    authDomain: 'tbcare-b9252.firebaseapp.com',
    storageBucket: 'tbcare-b9252.firebasestorage.app',
    measurementId: 'G-2VSL3PDE1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1XzoY19r0vh6E6unOxE-RjbmwAMd7O5U',
    appId: '1:1046347342722:android:253cf4a8608c9ea1a2a59b',
    messagingSenderId: '1046347342722',
    projectId: 'tbcare-b9252',
    storageBucket: 'tbcare-b9252.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo00Xxy7x55CYsydARRwuqouzm95EZOmU',
    appId: '1:1046347342722:ios:87f598f667abd1dfa2a59b',
    messagingSenderId: '1046347342722',
    projectId: 'tbcare-b9252',
    storageBucket: 'tbcare-b9252.firebasestorage.app',
    iosBundleId: 'com.example.tbcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo00Xxy7x55CYsydARRwuqouzm95EZOmU',
    appId: '1:1046347342722:ios:87f598f667abd1dfa2a59b',
    messagingSenderId: '1046347342722',
    projectId: 'tbcare-b9252',
    storageBucket: 'tbcare-b9252.firebasestorage.app',
    iosBundleId: 'com.example.tbcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiJdVLhqCT-dhoYXnHxpemiU-_EA_LkOI',
    appId: '1:1046347342722:web:69cc8932eb06f314a2a59b',
    messagingSenderId: '1046347342722',
    projectId: 'tbcare-b9252',
    authDomain: 'tbcare-b9252.firebaseapp.com',
    storageBucket: 'tbcare-b9252.firebasestorage.app',
    measurementId: 'G-5RTWBNKFPM',
  );
}
